---
packages:
- name: nginx
  ensure: 1.4.6-1ubuntu3.9
- name: php5-fpm
  ensure: 5.5.9+dfsg-1ubuntu4.29
files:
- filename: /etc/nginx/sites-available/default
  source: files/webserver.conf
  owner: root
  group: root
  mode: "0644"
  trigger: nginx
- filename: /usr/share/nginx/html/index.php
  source: files/index.php
  owner: root
  group: root
  mode: "0644"
  trigger: ""
